### ISSUE TITLE
Should work as a mobile page also

### ISSUE THREAD

**Issue by DangerBlack** [joshka/xkcd-with-alt-text#2]
It should work as a web page in addition to rss feed.
Can be really useful in some situation. 
Thanks btw

**Comment by joshka** [comment]
Good idea - I haven't touched this in eleventy-bajillion internet years though. I'm more surprised that it's even still working. Happy to apply a PR though if you're willing.

**Comment by joshka** [comment]
I know this was a while ago, and I'm not certain whether I fully understand what you're looking for.
Does https://m.xkcd.com/ work for your situation?

**Comment by joshka** [comment]
Closing as stale - feel free to reopen with more details if you'd like.
