### ISSUE TITLE
Mime type is text/html.

### ISSUE THREAD

**Issue by kevincox** [joshka/xkcd-with-alt-text#6]
The feed has the wrong MIME type, it should presumably pass though the source mime time based on how it is passing though the source data.

**Comment by joshka** [comment]
Thanks - that's a good catch. It's been long enough since I deployed this that it's running on a heroku stack that was deprecated a couple of years back. It'll take a bit for me to get back to understanding how this is running :D

**Comment by joshka** [comment]
Fixed in https://github.com/joshka/xkcd-with-alt-text/commit/29d7dd6eb52608379b0e4d7488608a0618b7fa6f

xkcd rss seems to only return 'text/xml' regardless of what you ask for. 🤷‍♂️
